export { default as Img1 } from './Img1.jpg';
export { default as Img2 } from './Img2.jpg';
export { default as Img3 } from './Img3.jpg';
export { default as Img4 } from './Img4.jpg';
export { default as Img5 } from './Img5.jpg';
export { default as Img6 } from './Img6.jpg';
export { default as Img7 } from './Img7.jpg';
export { default as Img8 } from './Img8.jpg';
export { default as Roteiro } from './Roteiro.pdf';
